### ISSUE TITLE
Spelled Punnett Square Wrong!

### ISSUE THREAD

**Issue by ImDaRealAni** [GrandMoff100/ReallyBigPunnetSquares#1]
If you want, I can send a PR and change everything.

**Comment by GrandMoff100** [comment]
Please do!

**Comment by GrandMoff100** [comment]
Hows that PR coming @ImDaRealAni?

**Comment by ImDaRealAni** [comment]
Did it! Nice project! I also remember learning about Punnett Squares!

**Comment by GrandMoff100** [comment]
Punnett squares are really fun.
